name: contrastive_2006_stl10
dataset: stl10
num_workers: 0

loss_type: contrastive_2006
lambda_c: 1.0

backbone: resnet18
emb_dim: 128
batch_size: 256
epochs: 200
lr: 0.001

early_stopping:
  enable: true
  patience: 20
